### PR TITLE
Update script to use new olm manifest formats

### PR DESCRIPTION
**Pull request by jordigilh**
This change updates the manifest format in the graph.yaml files that comes from using opm version 1.47. This opm version supports backwards compatibility as well as support for OCP 4.17+.

It also fixes the `generate-fbc.sh` script and now it is able to generate the `graph.yaml` file directly from the red hat catalog. It is also able to add a line comment that contains the release version to each of the bundles listed in the `graph.yaml`.

Example:
* Generate the graph.yaml for each OCP version: `./generate-fbc.sh --init-basic-all yq` (note that 4.13 fails because it contains no image listed. I think it's because our base image in the `catalog.Dockefile` is pointing to v4.14. Note that this PR fixes that)
* Auto generate the comments based on the release label in the bundle: `./generate-fbc.sh --comment-graph-all`

It is possible to be more specific `./generate-fbc.sh --comment-graph v4.16 yq` or `./generate-fbc.sh --comment-graph v4.16`.

@jenniferubah PTAL.

### CODE REVIEW

**Comment by jenniferubah** [comment]
> This change updates the manifest format in the graph.yaml files that comes from using opm version 1.47. This opm version supports backwards compatibility as well as support for OCP 4.17+.
> 
> It also fixes the `generate-fbc.sh` script and now it is able to generate the `graph.yaml` file directly from the red hat catalog. It is also able to add a line comment that contains the release version to each of the bundles listed in the `graph.yaml`.
> 
> Example:
> 
> * Generate the graph.yaml for each OCP version: `./generate-fbc.sh --init-basic-all yq` (note that 4.13 fails because it contains no image listed. I think it's because our base image in the `catalog.Dockefile` is pointing to v4.14. Note that this PR fixes that)
> * Auto generate the comments based on the release label in the bundle: `./generate-fbc.sh --comment-graph-all`
> 
> It is possible to be more specific `./generate-fbc.sh --comment-graph v4.16 yq` or `./generate-fbc.sh --comment-graph v4.16`.
> 
> @jenniferubah PTAL.

So far, looks really good. Was able to test and play around with `generate-fbc.sh` and see what was happening. Just had a few questions for my knowledge check. Once we have our pipelines back up, will test some more.

**Comment by jordigilh** [comment]
> > This change updates the manifest format in the graph.yaml files that comes from using opm version 1.47. This opm version supports backwards compatibility as well as support for OCP 4.17+.
> > It also fixes the `generate-fbc.sh` script and now it is able to generate the `graph.yaml` file directly from the red hat catalog. It is also able to add a line comment that contains the release version to each of the bundles listed in the `graph.yaml`.
> > Example:
> > 
> > * Generate the graph.yaml for each OCP version: `./generate-fbc.sh --init-basic-all yq` (note that 4.13 fails because it contains no image listed. I think it's because our base image in the `catalog.Dockefile` is pointing to v4.14. Note that this PR fixes that)
> > * Auto generate the comments based on the release label in the bundle: `./generate-fbc.sh --comment-graph-all`
> > 
> > It is possible to be more specific `./generate-fbc.sh --comment-graph v4.16 yq` or `./generate-fbc.sh --comment-graph v4.16`.
> > @jenniferubah PTAL.
> 
> So far, looks really good. Was able to test and play around with `generate-fbc.sh` and see what was happening. Just had a few questions for my knowledge check. Once we have our pipelines back up, will test some more.

ok so we wait until they're up and running to make sure nothing breaks up :)

**Pull request merged**
